
server:
  port: 8989
spring:
  application:
    name: Registry-Service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-files
